/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum BridgeGain {
	GAIN_1X(1) {
		public String getMessage() {
			return ("1x");
		}
	},
	GAIN_2X(2) {
		public String getMessage() {
			return ("2x");
		}
	},
	GAIN_4X(3) {
		public String getMessage() {
			return ("4x");
		}
	},
	GAIN_8X(4) {
		public String getMessage() {
			return ("8x");
		}
	},
	GAIN_16X(5) {
		public String getMessage() {
			return ("16x");
		}
	},
	GAIN_32X(6) {
		public String getMessage() {
			return ("32x");
		}
	},
	GAIN_64X(7) {
		public String getMessage() {
			return ("64x");
		}
	},
	GAIN_128X(8) {
		public String getMessage() {
			return ("128x");
		}
	};

	public static BridgeGain getEnum(int code) {
		switch(code) {
		case 1:
			return GAIN_1X;
		case 2:
			return GAIN_2X;
		case 3:
			return GAIN_4X;
		case 4:
			return GAIN_8X;
		case 5:
			return GAIN_16X;
		case 6:
			return GAIN_32X;
		case 7:
			return GAIN_64X;
		case 8:
			return GAIN_128X;
		}
		return null;
	}

	private final int code;
	private BridgeGain(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
