/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

import java.util.Arrays;

public class CurrentInputCurrentChangeEvent {

	CurrentInput Source;
	double Current;
	public CurrentInputCurrentChangeEvent(CurrentInput Source, double current) {
		this.Source = Source;
		this.Current = current;
	}
	public CurrentInput getSource() {
		return Source;
	}
	public double getCurrent() {
		return Current;
	}
	public String toString() {
		return "[CurrentInputCurrentChangeEvent](" +
			"Source: " + Source + ", " +
			"Current: " + Current +
			")";
	}
}
