/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum DeviceID {
	NONE(0) {
		public String getMessage() {
			return ("Unknown device");
		}
	},
	PN_INTERFACE_KIT488(1) {
		public String getMessage() {
			return ("PhidgetInterfaceKit 4/8/8");
		}
	},
	PN_1000(2) {
		public String getMessage() {
			return ("PhidgetServo 1-Motor (1000)");
		}
	},
	PN_1001(3) {
		public String getMessage() {
			return ("PhidgetServo 4-Motor (1001)");
		}
	},
	PN_1002(4) {
		public String getMessage() {
			return ("PhidgetAnalog 4-Output (1002)");
		}
	},
	PN_1008(5) {
		public String getMessage() {
			return ("PhidgetAccelerometer 2-Axis (1008)");
		}
	},
	PN_1010_1013_1018_1019(6) {
		public String getMessage() {
			return ("PhidgetInterfaceKit 8/8/8 (1010, 1013, 1018, 1019)");
		}
	},
	PN_1011(7) {
		public String getMessage() {
			return ("PhidgetInterfaceKit 2/2/2 (1011)");
		}
	},
	PN_1012(8) {
		public String getMessage() {
			return ("PhidgetInterfaceKit 0/16/16 (1012)");
		}
	},
	PN_1014(9) {
		public String getMessage() {
			return ("PhidgetInterfaceKit 0/0/4 (1014)");
		}
	},
	PN_1015(10) {
		public String getMessage() {
			return ("PhidgetLinearTouch (1015)");
		}
	},
	PN_1016(11) {
		public String getMessage() {
			return ("PhidgetCircularTouch (1016)");
		}
	},
	PN_1017(12) {
		public String getMessage() {
			return ("PhidgetInterfaceKit 0/0/8 (1017)");
		}
	},
	PN_1023(13) {
		public String getMessage() {
			return ("PhidgetRFID (1023)");
		}
	},
	PN_1024(14) {
		public String getMessage() {
			return ("PhidgetRFID Read-Write (1024)");
		}
	},
	PN_1030(15) {
		public String getMessage() {
			return ("PhidgetLED-64 (1030)");
		}
	},
	PN_1031(16) {
		public String getMessage() {
			return ("PhidgetLED-64 Advanced (1031)");
		}
	},
	PN_1032(17) {
		public String getMessage() {
			return ("PhidgetLED-64 Advanced (1032)");
		}
	},
	PN_1040(18) {
		public String getMessage() {
			return ("PhidgetGPS (1040)");
		}
	},
	PN_1041(19) {
		public String getMessage() {
			return ("PhidgetSpatial 0/0/3 Basic (1041)");
		}
	},
	PN_1042(20) {
		public String getMessage() {
			return ("PhidgetSpatial 3/3/3 Basic (1042)");
		}
	},
	PN_1043(21) {
		public String getMessage() {
			return ("PhidgetSpatial Precision 0/0/3 High Resolution (1043)");
		}
	},
	PN_1044(22) {
		public String getMessage() {
			return ("PhidgetSpatial Precision 3/3/3 High Resolution (1044)");
		}
	},
	PN_1045(23) {
		public String getMessage() {
			return ("PhidgetTemperatureSensor IR (1045)");
		}
	},
	PN_1046(24) {
		public String getMessage() {
			return ("PhidgetBridge 4-Input (1046)");
		}
	},
	PN_1047(25) {
		public String getMessage() {
			return ("PhidgetEncoder HighSpeed 4-Input (1047)");
		}
	},
	PN_1048(26) {
		public String getMessage() {
			return ("PhidgetTemperatureSensor 4-input (1048)");
		}
	},
	PN_1049(27) {
		public String getMessage() {
			return ("PhidgetSpatial 0/0/3 (1049)");
		}
	},
	PN_1051(28) {
		public String getMessage() {
			return ("PhidgetTemperatureSensor 1-Input (1051)");
		}
	},
	PN_1052(29) {
		public String getMessage() {
			return ("PhidgetEncoder Mechanical (1052)");
		}
	},
	PN_1053(30) {
		public String getMessage() {
			return ("PhidgetAccelerometer 2-Axis (1053)");
		}
	},
	PN_1054(31) {
		public String getMessage() {
			return ("PhidgetFrequencyCounter (1054)");
		}
	},
	PN_1055(32) {
		public String getMessage() {
			return ("PhidgetIR (1055)");
		}
	},
	PN_1056(33) {
		public String getMessage() {
			return ("PhidgetSpatial 3/3/3 (1056)");
		}
	},
	PN_1057(34) {
		public String getMessage() {
			return ("PhidgetEncoder HighSpeed (1057)");
		}
	},
	PN_1058(35) {
		public String getMessage() {
			return ("PhidgetPHSensor (1058)");
		}
	},
	PN_1059(36) {
		public String getMessage() {
			return ("PhidgetAccelerometer 3-Axis (1059)");
		}
	},
	PN_1060(37) {
		public String getMessage() {
			return ("PhidgetMotorControl LV (1060)");
		}
	},
	PN_1061(38) {
		public String getMessage() {
			return ("PhidgetAdvancedServo 8-Motor (1061)");
		}
	},
	PN_1062(39) {
		public String getMessage() {
			return ("PhidgetStepper Unipolar 4-Motor (1062)");
		}
	},
	PN_1063(40) {
		public String getMessage() {
			return ("PhidgetStepper Bipolar 1-Motor (1063)");
		}
	},
	PN_1064(41) {
		public String getMessage() {
			return ("PhidgetMotorControl HC (1064)");
		}
	},
	PN_1065(42) {
		public String getMessage() {
			return ("PhidgetMotorControl 1-Motor (1065)");
		}
	},
	PN_1066(43) {
		public String getMessage() {
			return ("PhidgetAdvancedServo 1-Motor (1066)");
		}
	},
	PN_1067(44) {
		public String getMessage() {
			return ("PhidgetStepper Bipolar HC (1067)");
		}
	},
	PN_1202_1203(45) {
		public String getMessage() {
			return ("PhidgetTextLCD 20x2 with PhidgetInterfaceKit 8/8/8 (1201, 1202, 1203)");
		}
	},
	PN_1204(46) {
		public String getMessage() {
			return ("PhidgetTextLCD Adapter (1204)");
		}
	},
	PN_1215__1218(47) {
		public String getMessage() {
			return ("PhidgetTextLCD 20x2 (1215/1216/1217/1218)");
		}
	},
	PN_1219__1222(48) {
		public String getMessage() {
			return ("PhidgetTextLCD 20x2 with PhidgetInterfaceKit 0/8/8 (1219, 1220, 1221, 1222)");
		}
	},
	PN_ADP1000(49) {
		public String getMessage() {
			return ("pH Adapter");
		}
	},
	PN_DAQ1000(51) {
		public String getMessage() {
			return ("Analog Input Module x8");
		}
	},
	PN_DAQ1200(52) {
		public String getMessage() {
			return ("Digital Input 4");
		}
	},
	PN_DAQ1300(53) {
		public String getMessage() {
			return ("Digital Input 4 Isolated");
		}
	},
	PN_DAQ1301(54) {
		public String getMessage() {
			return ("Digital Input 16");
		}
	},
	PN_DAQ1400(55) {
		public String getMessage() {
			return ("Versatile Input");
		}
	},
	PN_DAQ1500(56) {
		public String getMessage() {
			return ("Bridge");
		}
	},
	PN_DCC1000(57) {
		public String getMessage() {
			return ("DC Motor Controller with PID");
		}
	},
	PN_DST1000(58) {
		public String getMessage() {
			return ("200mm Distance Sensor");
		}
	},
	PN_DST1200(59) {
		public String getMessage() {
			return ("Sonar Distance Sensor");
		}
	},
	PN_ENC1000(60) {
		public String getMessage() {
			return ("Encoder");
		}
	},
	PN_HIN1000(61) {
		public String getMessage() {
			return ("Capacitive Touch Sensor");
		}
	},
	PN_HIN1001(62) {
		public String getMessage() {
			return ("Capacitive Scroll");
		}
	},
	PN_HIN1100(63) {
		public String getMessage() {
			return ("Joystick");
		}
	},
	PN_HUB0000(64) {
		public String getMessage() {
			return ("Phidget Hub with 6 ports");
		}
	},
	PN_HUB0004(67) {
		public String getMessage() {
			return ("Phidget SPI VINT Hub with 6 ports");
		}
	},
	PN_HUM1000(69) {
		public String getMessage() {
			return ("Humidity Sensor");
		}
	},
	PN_LCD1100(70) {
		public String getMessage() {
			return ("LCD");
		}
	},
	PN_LED1000(71) {
		public String getMessage() {
			return ("LED Driver 32");
		}
	},
	PN_LUX1000(72) {
		public String getMessage() {
			return ("Light Sensor");
		}
	},
	PN_MOT1100(73) {
		public String getMessage() {
			return ("Accelerometer 0/0/3");
		}
	},
	PN_MOT1101(74) {
		public String getMessage() {
			return ("Spatial 3/3/3");
		}
	},
	PN_OUT1000(75) {
		public String getMessage() {
			return ("Analog Output 0-5V");
		}
	},
	PN_OUT1001(76) {
		public String getMessage() {
			return ("Analog Output (+/-)10V");
		}
	},
	PN_OUT1002(77) {
		public String getMessage() {
			return ("Analog Output (+/-)10V - 16 bit");
		}
	},
	PN_OUT1100(78) {
		public String getMessage() {
			return ("Digital Output 4");
		}
	},
	PN_PRE1000(79) {
		public String getMessage() {
			return ("Barometer");
		}
	},
	PN_RCC1000(80) {
		public String getMessage() {
			return ("8-Servo Controller");
		}
	},
	PN_REL1000(81) {
		public String getMessage() {
			return ("Power Relay 4");
		}
	},
	PN_REL1100(82) {
		public String getMessage() {
			return ("Digital Output 4 Isolated");
		}
	},
	PN_REL1101(83) {
		public String getMessage() {
			return ("Digital Output 16 Isolated");
		}
	},
	PN_SAF1000(84) {
		public String getMessage() {
			return ("Power Supply Protector");
		}
	},
	PN_SND1000(85) {
		public String getMessage() {
			return ("Sound Pressure Level Sensor");
		}
	},
	PN_STC1000(86) {
		public String getMessage() {
			return ("Bipolar Stepper Motor Controller");
		}
	},
	PN_TMP1000(87) {
		public String getMessage() {
			return ("Integrated Temperature Sensor");
		}
	},
	PN_TMP1100(88) {
		public String getMessage() {
			return ("Thermocouple 1");
		}
	},
	PN_TMP1101(89) {
		public String getMessage() {
			return ("Thermocouple 4");
		}
	},
	PN_TMP1200(90) {
		public String getMessage() {
			return ("RTD");
		}
	},
	PN_VCP1000(92) {
		public String getMessage() {
			return ("Voltage Sensor High Precision");
		}
	},
	PN_VCP1001(93) {
		public String getMessage() {
			return ("Voltage Sensor Large");
		}
	},
	PN_VCP1002(94) {
		public String getMessage() {
			return ("Voltage Sensor Small");
		}
	},
	DIGITAL_INPUT_PORT(95) {
		public String getMessage() {
			return ("Hub Port in Digital Input mode");
		}
	},
	DIGITAL_OUTPUT_PORT(96) {
		public String getMessage() {
			return ("Hub Port in Digital Output mode");
		}
	},
	VOLTAGE_INPUT_PORT(97) {
		public String getMessage() {
			return ("Hub Port in Voltage Input mode");
		}
	},
	VOLTAGE_RATIO_INPUT_PORT(98) {
		public String getMessage() {
			return ("Hub Port in Voltage Ratio Input mode");
		}
	},
	PN_VCP1100(105) {
		public String getMessage() {
			return ("30A Current Sensor");
		}
	},
	PN_DCC1100(108) {
		public String getMessage() {
			return ("BLDC Motor Controller");
		}
	},
	PN_HIN1101(109) {
		public String getMessage() {
			return ("Dial Encoder");
		}
	},
	PN_DCC1001(110) {
		public String getMessage() {
			return ("Small DC Motor Controller");
		}
	},
	PN_DICTIONARY(111) {
		public String getMessage() {
			return ("Dictionary");
		}
	},
	PN_STC1001(115) {
		public String getMessage() {
			return ("Bipolar Stepper Motor SmallController");
		}
	};

	public static DeviceID getEnum(int code) {
		switch(code) {
		case 0:
			return NONE;
		case 1:
			return PN_INTERFACE_KIT488;
		case 2:
			return PN_1000;
		case 3:
			return PN_1001;
		case 4:
			return PN_1002;
		case 5:
			return PN_1008;
		case 6:
			return PN_1010_1013_1018_1019;
		case 7:
			return PN_1011;
		case 8:
			return PN_1012;
		case 9:
			return PN_1014;
		case 10:
			return PN_1015;
		case 11:
			return PN_1016;
		case 12:
			return PN_1017;
		case 13:
			return PN_1023;
		case 14:
			return PN_1024;
		case 15:
			return PN_1030;
		case 16:
			return PN_1031;
		case 17:
			return PN_1032;
		case 18:
			return PN_1040;
		case 19:
			return PN_1041;
		case 20:
			return PN_1042;
		case 21:
			return PN_1043;
		case 22:
			return PN_1044;
		case 23:
			return PN_1045;
		case 24:
			return PN_1046;
		case 25:
			return PN_1047;
		case 26:
			return PN_1048;
		case 27:
			return PN_1049;
		case 28:
			return PN_1051;
		case 29:
			return PN_1052;
		case 30:
			return PN_1053;
		case 31:
			return PN_1054;
		case 32:
			return PN_1055;
		case 33:
			return PN_1056;
		case 34:
			return PN_1057;
		case 35:
			return PN_1058;
		case 36:
			return PN_1059;
		case 37:
			return PN_1060;
		case 38:
			return PN_1061;
		case 39:
			return PN_1062;
		case 40:
			return PN_1063;
		case 41:
			return PN_1064;
		case 42:
			return PN_1065;
		case 43:
			return PN_1066;
		case 44:
			return PN_1067;
		case 45:
			return PN_1202_1203;
		case 46:
			return PN_1204;
		case 47:
			return PN_1215__1218;
		case 48:
			return PN_1219__1222;
		case 49:
			return PN_ADP1000;
		case 51:
			return PN_DAQ1000;
		case 52:
			return PN_DAQ1200;
		case 53:
			return PN_DAQ1300;
		case 54:
			return PN_DAQ1301;
		case 55:
			return PN_DAQ1400;
		case 56:
			return PN_DAQ1500;
		case 57:
			return PN_DCC1000;
		case 58:
			return PN_DST1000;
		case 59:
			return PN_DST1200;
		case 60:
			return PN_ENC1000;
		case 61:
			return PN_HIN1000;
		case 62:
			return PN_HIN1001;
		case 63:
			return PN_HIN1100;
		case 64:
			return PN_HUB0000;
		case 67:
			return PN_HUB0004;
		case 69:
			return PN_HUM1000;
		case 70:
			return PN_LCD1100;
		case 71:
			return PN_LED1000;
		case 72:
			return PN_LUX1000;
		case 73:
			return PN_MOT1100;
		case 74:
			return PN_MOT1101;
		case 75:
			return PN_OUT1000;
		case 76:
			return PN_OUT1001;
		case 77:
			return PN_OUT1002;
		case 78:
			return PN_OUT1100;
		case 79:
			return PN_PRE1000;
		case 80:
			return PN_RCC1000;
		case 81:
			return PN_REL1000;
		case 82:
			return PN_REL1100;
		case 83:
			return PN_REL1101;
		case 84:
			return PN_SAF1000;
		case 85:
			return PN_SND1000;
		case 86:
			return PN_STC1000;
		case 87:
			return PN_TMP1000;
		case 88:
			return PN_TMP1100;
		case 89:
			return PN_TMP1101;
		case 90:
			return PN_TMP1200;
		case 92:
			return PN_VCP1000;
		case 93:
			return PN_VCP1001;
		case 94:
			return PN_VCP1002;
		case 95:
			return DIGITAL_INPUT_PORT;
		case 96:
			return DIGITAL_OUTPUT_PORT;
		case 97:
			return VOLTAGE_INPUT_PORT;
		case 98:
			return VOLTAGE_RATIO_INPUT_PORT;
		case 105:
			return PN_VCP1100;
		case 108:
			return PN_DCC1100;
		case 109:
			return PN_HIN1101;
		case 110:
			return PN_DCC1001;
		case 111:
			return PN_DICTIONARY;
		case 115:
			return PN_STC1001;
		}
		return null;
	}

	private final int code;
	private DeviceID(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
