/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;
import java.util.*;

public class DigitalOutputBase extends Phidget {

	DigitalOutputBase(long handle) {
		super(handle);
	}

	public DigitalOutputBase() throws PhidgetException {
		super(create());
	}

	private native static long create() throws PhidgetException;

	private final void setDeviceEvents(boolean enable) {
	}


	public native double getDutyCycle() throws PhidgetException;
	public native void setDutyCycle(double DutyCycle) throws PhidgetException;
	public native void setDutyCycle(double DutyCycle, AsyncListener asyncHandler);
	public native double getMinDutyCycle() throws PhidgetException;
	public native double getMaxDutyCycle() throws PhidgetException;
	public native double getLEDCurrentLimit() throws PhidgetException;
	public native void setLEDCurrentLimit(double LEDCurrentLimit, AsyncListener asyncHandler);
	public native void setLEDCurrentLimit(double LEDCurrentLimit) throws PhidgetException;
	public native double getMinLEDCurrentLimit() throws PhidgetException;
	public native double getMaxLEDCurrentLimit() throws PhidgetException;
	public native LEDForwardVoltage getLEDForwardVoltage() throws PhidgetException;
	public native void setLEDForwardVoltage(LEDForwardVoltage LEDForwardVoltage) throws PhidgetException;
	public native boolean getState() throws PhidgetException;
	public native void setState(boolean State) throws PhidgetException;
	public native void setState(boolean State, AsyncListener asyncHandler);
}
