/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum EncoderIOMode {
	PUSH_PULL(1) {
		public String getMessage() {
			return ("Push-Pull");
		}
	},
	LINE_DRIVER_2K2(2) {
		public String getMessage() {
			return ("Line Driver 2.2K");
		}
	},
	LINE_DRIVER_10K(3) {
		public String getMessage() {
			return ("Line Driver 10K");
		}
	},
	OPEN_COLLECTOR_2K2(4) {
		public String getMessage() {
			return ("Open Collector 2.2K");
		}
	},
	OPEN_COLLECTOR_10K(5) {
		public String getMessage() {
			return ("Open Collector 10K");
		}
	};

	public static EncoderIOMode getEnum(int code) {
		switch(code) {
		case 1:
			return PUSH_PULL;
		case 2:
			return LINE_DRIVER_2K2;
		case 3:
			return LINE_DRIVER_10K;
		case 4:
			return OPEN_COLLECTOR_2K2;
		case 5:
			return OPEN_COLLECTOR_10K;
		}
		return null;
	}

	private final int code;
	private EncoderIOMode(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
