/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum HubPortMode {
	VINT(0) {
		public String getMessage() {
			return ("VINT");
		}
	},
	DIGITAL_INPUT(1) {
		public String getMessage() {
			return ("Digital Input");
		}
	},
	DIGITAL_OUTPUT(2) {
		public String getMessage() {
			return ("Digital Output");
		}
	},
	VOLTAGE_INPUT(3) {
		public String getMessage() {
			return ("Voltage Input");
		}
	},
	VOLTAGE_RATIO_INPUT(4) {
		public String getMessage() {
			return ("Voltage Ratio Input");
		}
	};

	public static HubPortMode getEnum(int code) {
		switch(code) {
		case 0:
			return VINT;
		case 1:
			return DIGITAL_INPUT;
		case 2:
			return DIGITAL_OUTPUT;
		case 3:
			return VOLTAGE_INPUT;
		case 4:
			return VOLTAGE_RATIO_INPUT;
		}
		return null;
	}

	private final int code;
	private HubPortMode(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
