/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum IRCodeEncoding {
	UNKNOWN(1) {
		public String getMessage() {
			return ("Unknown");
		}
	},
	SPACE(2) {
		public String getMessage() {
			return ("Space");
		}
	},
	PULSE(3) {
		public String getMessage() {
			return ("Pulse");
		}
	},
	BI_PHASE(4) {
		public String getMessage() {
			return ("BiPhase");
		}
	},
	RC5(5) {
		public String getMessage() {
			return ("RC5");
		}
	},
	RC6(6) {
		public String getMessage() {
			return ("RC6");
		}
	};

	public static IRCodeEncoding getEnum(int code) {
		switch(code) {
		case 1:
			return UNKNOWN;
		case 2:
			return SPACE;
		case 3:
			return PULSE;
		case 4:
			return BI_PHASE;
		case 5:
			return RC5;
		case 6:
			return RC6;
		}
		return null;
	}

	private final int code;
	private IRCodeEncoding(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
