/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

import java.util.Arrays;

public class IRLearnEvent {

	IR Source;
	java.lang.String Code;
	IRCodeInfo CodeInfo;
	public IRLearnEvent(IR Source, java.lang.String code, IRCodeInfo codeInfo) {
		this.Source = Source;
		this.Code = code;
		this.CodeInfo = codeInfo;
	}
	public IR getSource() {
		return Source;
	}
	public java.lang.String getCode() {
		return Code;
	}
	public IRCodeInfo getCodeInfo() {
		return CodeInfo;
	}
	public String toString() {
		return "[IRLearnEvent](" +
			"Source: " + Source + ", " +
			"Code: " + Code + ", " +
			"CodeInfo: " + CodeInfo +
			")";
	}
}
