/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum LCDScreenSize {
	NO_SCREEN(1) {
		public String getMessage() {
			return ("No Screen");
		}
	},
	DIMENSIONS_1X8(2) {
		public String getMessage() {
			return ("1x8");
		}
	},
	DIMENSIONS_2X8(3) {
		public String getMessage() {
			return ("2x8");
		}
	},
	DIMENSIONS_1X16(4) {
		public String getMessage() {
			return ("1x16");
		}
	},
	DIMENSIONS_2X16(5) {
		public String getMessage() {
			return ("2x16");
		}
	},
	DIMENSIONS_4X16(6) {
		public String getMessage() {
			return ("4x16");
		}
	},
	DIMENSIONS_2X20(7) {
		public String getMessage() {
			return ("2x20");
		}
	},
	DIMENSIONS_4X20(8) {
		public String getMessage() {
			return ("4x20");
		}
	},
	DIMENSIONS_2X24(9) {
		public String getMessage() {
			return ("2x24");
		}
	},
	DIMENSIONS_1X40(10) {
		public String getMessage() {
			return ("1x40");
		}
	},
	DIMENSIONS_2X40(11) {
		public String getMessage() {
			return ("2x40");
		}
	},
	DIMENSIONS_4X40(12) {
		public String getMessage() {
			return ("4x40");
		}
	},
	DIMENSIONS_64X128(13) {
		public String getMessage() {
			return ("64x128");
		}
	};

	public static LCDScreenSize getEnum(int code) {
		switch(code) {
		case 1:
			return NO_SCREEN;
		case 2:
			return DIMENSIONS_1X8;
		case 3:
			return DIMENSIONS_2X8;
		case 4:
			return DIMENSIONS_1X16;
		case 5:
			return DIMENSIONS_2X16;
		case 6:
			return DIMENSIONS_4X16;
		case 7:
			return DIMENSIONS_2X20;
		case 8:
			return DIMENSIONS_4X20;
		case 9:
			return DIMENSIONS_2X24;
		case 10:
			return DIMENSIONS_1X40;
		case 11:
			return DIMENSIONS_2X40;
		case 12:
			return DIMENSIONS_4X40;
		case 13:
			return DIMENSIONS_64X128;
		}
		return null;
	}

	private final int code;
	private LCDScreenSize(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
