/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum LEDForwardVoltage {
	VOLTS_1_7(1) {
		public String getMessage() {
			return ("1.7 V");
		}
	},
	VOLTS_2_75(2) {
		public String getMessage() {
			return ("2.75 V");
		}
	},
	VOLTS_3_2(3) {
		public String getMessage() {
			return ("3.2 V");
		}
	},
	VOLTS_3_9(4) {
		public String getMessage() {
			return ("3.9 V");
		}
	},
	VOLTS_4_0(5) {
		public String getMessage() {
			return ("4.0 V");
		}
	},
	VOLTS_4_8(6) {
		public String getMessage() {
			return ("4.8 V");
		}
	},
	VOLTS_5_0(7) {
		public String getMessage() {
			return ("5.0 V");
		}
	},
	VOLTS_5_6(8) {
		public String getMessage() {
			return ("5.6 V");
		}
	};

	public static LEDForwardVoltage getEnum(int code) {
		switch(code) {
		case 1:
			return VOLTS_1_7;
		case 2:
			return VOLTS_2_75;
		case 3:
			return VOLTS_3_2;
		case 4:
			return VOLTS_3_9;
		case 5:
			return VOLTS_4_0;
		case 6:
			return VOLTS_4_8;
		case 7:
			return VOLTS_5_0;
		case 8:
			return VOLTS_5_6;
		}
		return null;
	}

	private final int code;
	private LEDForwardVoltage(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
