/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum RFIDProtocol {
	EM4100(1) {
		public String getMessage() {
			return ("EM4100");
		}
	},
	ISO11785_FDX_B(2) {
		public String getMessage() {
			return ("ISO11785 FDX B");
		}
	},
	PHIDGET_TAG(3) {
		public String getMessage() {
			return ("PhidgetTAG");
		}
	};

	public static RFIDProtocol getEnum(int code) {
		switch(code) {
		case 1:
			return EM4100;
		case 2:
			return ISO11785_FDX_B;
		case 3:
			return PHIDGET_TAG;
		}
		return null;
	}

	private final int code;
	private RFIDProtocol(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
