/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum RTDType {
	PT100_3850(1) {
		public String getMessage() {
			return ("PT100 3850");
		}
	},
	PT1000_3850(2) {
		public String getMessage() {
			return ("PT1000 3850");
		}
	},
	PT100_3920(3) {
		public String getMessage() {
			return ("PT100 3920");
		}
	},
	PT1000_3920(4) {
		public String getMessage() {
			return ("PT1000 3920");
		}
	};

	public static RTDType getEnum(int code) {
		switch(code) {
		case 1:
			return PT100_3850;
		case 2:
			return PT1000_3850;
		case 3:
			return PT100_3920;
		case 4:
			return PT1000_3920;
		}
		return null;
	}

	private final int code;
	private RTDType(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
