/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum VoltageRange {
	MILLIVOLTS_10(1) {
		public String getMessage() {
			return ("10 mV");
		}
	},
	MILLIVOLTS_40(2) {
		public String getMessage() {
			return ("40 mV");
		}
	},
	MILLIVOLTS_200(3) {
		public String getMessage() {
			return ("200 mV");
		}
	},
	MILLIVOLTS_312_5(4) {
		public String getMessage() {
			return ("312.5 mV");
		}
	},
	MILLIVOLTS_400(5) {
		public String getMessage() {
			return ("400 mV");
		}
	},
	MILLIVOLTS_1000(6) {
		public String getMessage() {
			return ("1000 mV");
		}
	},
	VOLTS_2(7) {
		public String getMessage() {
			return ("2 V");
		}
	},
	VOLTS_5(8) {
		public String getMessage() {
			return ("5 V");
		}
	},
	VOLTS_15(9) {
		public String getMessage() {
			return ("15 V");
		}
	},
	VOLTS_40(10) {
		public String getMessage() {
			return ("40 V");
		}
	},
	AUTO(11) {
		public String getMessage() {
			return ("Auto");
		}
	};

	public static VoltageRange getEnum(int code) {
		switch(code) {
		case 1:
			return MILLIVOLTS_10;
		case 2:
			return MILLIVOLTS_40;
		case 3:
			return MILLIVOLTS_200;
		case 4:
			return MILLIVOLTS_312_5;
		case 5:
			return MILLIVOLTS_400;
		case 6:
			return MILLIVOLTS_1000;
		case 7:
			return VOLTS_2;
		case 8:
			return VOLTS_5;
		case 9:
			return VOLTS_15;
		case 10:
			return VOLTS_40;
		case 11:
			return AUTO;
		}
		return null;
	}

	private final int code;
	private VoltageRange(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
