/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;
import java.util.*;

public class VoltageOutputBase extends Phidget {

	VoltageOutputBase(long handle) {
		super(handle);
	}

	public VoltageOutputBase() throws PhidgetException {
		super(create());
	}

	private native static long create() throws PhidgetException;

	private final void setDeviceEvents(boolean enable) {
	}


	public native void setEnabled(boolean Enabled) throws PhidgetException;
	public native boolean getEnabled() throws PhidgetException;
	public native double getVoltage() throws PhidgetException;
	public native void setVoltage(double Voltage) throws PhidgetException;
	public native void setVoltage(double Voltage, AsyncListener asyncHandler);
	public native double getMinVoltage() throws PhidgetException;
	public native double getMaxVoltage() throws PhidgetException;
	public native VoltageOutputRange getVoltageOutputRange() throws PhidgetException;
	public native void setVoltageOutputRange(VoltageOutputRange VoltageOutputRange) throws PhidgetException;
}
