/* DO NOT EDIT THIS FILE - it is machine generated */

/*
 * This file is part of Phidget22.jar
 *
 * Copyright 2017 Phidgets Inc <patrick@phidgets.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see
 * <http://www.gnu.org/licenses/>
 */

package com.phidget22;

public enum VoltageSensorType {
	VOLTAGE(0) {
		public String getMessage() {
			return ("Generic voltage sensor");
		}
	},
	PN_1114(11140) {
		public String getMessage() {
			return ("1114 - Temperature Sensor");
		}
	},
	PN_1117(11170) {
		public String getMessage() {
			return ("1117 - Voltage Sensor");
		}
	},
	PN_1123(11230) {
		public String getMessage() {
			return ("1123 - Precision Voltage Sensor");
		}
	},
	PN_1127(11270) {
		public String getMessage() {
			return ("1127 - Precision Light Sensor");
		}
	},
	PN_1130_PH(11301) {
		public String getMessage() {
			return ("1130 - pH Adapter");
		}
	},
	PN_1130_ORP(11302) {
		public String getMessage() {
			return ("1130 - ORP Adapter");
		}
	},
	PN_1132(11320) {
		public String getMessage() {
			return ("1132 - 4-20mA Adapter");
		}
	},
	PN_1133(11330) {
		public String getMessage() {
			return ("1133 - Sound Sensor");
		}
	},
	PN_1135(11350) {
		public String getMessage() {
			return ("1135 - Precision Voltage Sensor");
		}
	},
	PN_1142(11420) {
		public String getMessage() {
			return ("1142 - Light Sensor 1000 lux");
		}
	},
	PN_1143(11430) {
		public String getMessage() {
			return ("1143 - Light Sensor 70000 lux");
		}
	},
	PN_3500(35000) {
		public String getMessage() {
			return ("3500 - AC Current Sensor 10Amp");
		}
	},
	PN_3501(35010) {
		public String getMessage() {
			return ("3501 - AC Current Sensor 25Amp");
		}
	},
	PN_3502(35020) {
		public String getMessage() {
			return ("3502 - AC Current Sensor 50Amp");
		}
	},
	PN_3503(35030) {
		public String getMessage() {
			return ("3503 - AC Current Sensor 100Amp");
		}
	},
	PN_3507(35070) {
		public String getMessage() {
			return ("3507 - AC Voltage Sensor 0-250V (50Hz)");
		}
	},
	PN_3508(35080) {
		public String getMessage() {
			return ("3508 - AC Voltage Sensor 0-250V (60Hz)");
		}
	},
	PN_3509(35090) {
		public String getMessage() {
			return ("3509 - DC Voltage Sensor 0-200V");
		}
	},
	PN_3510(35100) {
		public String getMessage() {
			return ("3510 - DC Voltage Sensor 0-75V");
		}
	},
	PN_3511(35110) {
		public String getMessage() {
			return ("3511 - DC Current Sensor 0-10mA");
		}
	},
	PN_3512(35120) {
		public String getMessage() {
			return ("3512 - DC Current Sensor 0-100mA");
		}
	},
	PN_3513(35130) {
		public String getMessage() {
			return ("3513 - DC Current Sensor 0-1A");
		}
	},
	PN_3514(35140) {
		public String getMessage() {
			return ("3514 - AC Active Power Sensor 0-250V*0-30A (50Hz)");
		}
	},
	PN_3515(35150) {
		public String getMessage() {
			return ("3515 - AC Active Power Sensor 0-250V*0-30A (60Hz)");
		}
	},
	PN_3516(35160) {
		public String getMessage() {
			return ("3516 - AC Active Power Sensor 0-250V*0-5A (50Hz)");
		}
	},
	PN_3517(35170) {
		public String getMessage() {
			return ("3517 - AC Active Power Sensor 0-250V*0-5A (60Hz)");
		}
	},
	PN_3518(35180) {
		public String getMessage() {
			return ("3518 - AC Active Power Sensor 0-110V*0-5A (60Hz)");
		}
	},
	PN_3519(35190) {
		public String getMessage() {
			return ("3519 - AC Active Power Sensor 0-110V*0-15A (60Hz)");
		}
	},
	PN_3584(35840) {
		public String getMessage() {
			return ("3584 - 0-50A DC Current Transducer");
		}
	},
	PN_3585(35850) {
		public String getMessage() {
			return ("3585 - 0-100A DC Current Transducer");
		}
	},
	PN_3586(35860) {
		public String getMessage() {
			return ("3586 - 0-250A DC Current Transducer");
		}
	},
	PN_3587(35870) {
		public String getMessage() {
			return ("3587 - +-50A DC Current Transducer");
		}
	},
	PN_3588(35880) {
		public String getMessage() {
			return ("3588 - +-100A DC Current Transducer");
		}
	},
	PN_3589(35890) {
		public String getMessage() {
			return ("3589 - +-250A DC Current Transducer");
		}
	};

	public static VoltageSensorType getEnum(int code) {
		switch(code) {
		case 0:
			return VOLTAGE;
		case 11140:
			return PN_1114;
		case 11170:
			return PN_1117;
		case 11230:
			return PN_1123;
		case 11270:
			return PN_1127;
		case 11301:
			return PN_1130_PH;
		case 11302:
			return PN_1130_ORP;
		case 11320:
			return PN_1132;
		case 11330:
			return PN_1133;
		case 11350:
			return PN_1135;
		case 11420:
			return PN_1142;
		case 11430:
			return PN_1143;
		case 35000:
			return PN_3500;
		case 35010:
			return PN_3501;
		case 35020:
			return PN_3502;
		case 35030:
			return PN_3503;
		case 35070:
			return PN_3507;
		case 35080:
			return PN_3508;
		case 35090:
			return PN_3509;
		case 35100:
			return PN_3510;
		case 35110:
			return PN_3511;
		case 35120:
			return PN_3512;
		case 35130:
			return PN_3513;
		case 35140:
			return PN_3514;
		case 35150:
			return PN_3515;
		case 35160:
			return PN_3516;
		case 35170:
			return PN_3517;
		case 35180:
			return PN_3518;
		case 35190:
			return PN_3519;
		case 35840:
			return PN_3584;
		case 35850:
			return PN_3585;
		case 35860:
			return PN_3586;
		case 35870:
			return PN_3587;
		case 35880:
			return PN_3588;
		case 35890:
			return PN_3589;
		}
		return null;
	}

	private final int code;
	private VoltageSensorType(int code) {
		this.code = code;
	}

	public int getCode() {
		return (code);
	}

	public abstract String getMessage();
}
